# List of data sources (placeholder URLs)
# method: parser module name (example_html_table or example_json_endpoint)

defaults:
  state: MA
  loan_amount: 600000
  ltv: 80
  fico: 760
  lock_days: 30

sources:
  - name: DCU (Digital Federal Credit Union)
    org_type: credit_union
    homepage_url: https://www.dcu.org/
    rate_url: https://www.dcu.org/borrow/mortgage-loans/home-mortgage-loans.html
    method: dcu
    enabled: true
    notes: "Parses schema.org structured data"

  - name: Example CU B
    org_type: credit_union
    homepage_url: https://examplecub.org
    rate_url: https://api.examplecub.org/v1/rates
    method: example_json_endpoint
    enabled: true
    notes: "Sample JSON parser"

  - name: Placeholder Lender C
    org_type: lender
    homepage_url: https://placeholderlenderc.com
    rate_url: ""
    method: example_html_table
    enabled: false
    notes: "Fill in later"
