defaults:
  state: MA
  loan_amount: 600000
  ltv: 80
  fico: 760
  lock_days: 30

sources:
  # ========================================
  # Massachusetts Credit Unions (15)
  # ========================================
  
  - id: dcu
    name: DCU (Digital Federal Credit Union)
    org_type: credit_union
    homepage_url: https://www.dcu.org/
    rate_url: https://www.dcu.org/borrow/mortgage-loans/home-mortgage-loans.html
    parser_key: dcu
    enabled: true
    tags: [MA_local, cu]
    
  - id: rockland_fcu
    name: Rockland Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.rfcu.com/
    url: https://www.rfcu.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    notes: "Need to find rate page"
    
  - id: metro_cu
    name: Metro Credit Union (MA)
    org_type: credit_union
    homepage_url: https://www.metrocu.org/
    rate_url: https://www.metrocu.org/mortgage-rate-quote
    parser_key: metro_cu
    enabled: true
    tags: [MA_local, cu, needs_quote_flow]
    notes: "Attempting to parse quote page"
    
  - id: workers_cu
    name: Workers Credit Union
    org_type: credit_union
    homepage_url: https://www.wcu.com/
    url: https://www.wcu.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: jeanne_darc_cu
    name: "Jeanne D'Arc Credit Union"
    org_type: credit_union
    homepage_url: https://www.jdcu.org/
    url: https://www.jdcu.org/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: brightbridge_cu
    name: BrightBridge Credit Union
    org_type: credit_union
    homepage_url: https://www.brightbridge.com/
    url: https://www.brightbridge.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: hanscom_fcu
    name: Hanscom Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.hfcu.org/
    url: https://www.hfcu.org/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: greylock_fcu
    name: Greylock Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.greylock.org/
    url: https://www.greylock.org/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: webster_first_fcu
    name: Webster First Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.websterfirst.com/
    url: https://www.websterfirst.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: st_annes_cu
    name: St. Anne's Credit Union
    org_type: credit_union
    homepage_url: https://www.stannes.com/
    url: https://www.stannes.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: mit_fcu
    name: MIT Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.mitfcu.org/
    url: https://www.mitfcu.org/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: quincy_cu
    name: Quincy Credit Union
    org_type: credit_union
    homepage_url: https://www.qcu.org/
    url: https://www.qcu.org/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: umassfive_fcu
    name: UMassFive College Federal Credit Union
    org_type: credit_union
    homepage_url: https://umassfive.coop/
    url: https://umassfive.coop/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: city_of_boston_cu
    name: City of Boston Credit Union
    org_type: credit_union
    homepage_url: https://cityofbostoncu.com/
    url: https://cityofbostoncu.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  - id: align_cu
    name: Align Credit Union
    org_type: credit_union
    homepage_url: https://www.aligncu.com/
    url: https://www.aligncu.com/
    method: none
    enabled: false
    tags: [MA_local, cu]
    
  # ========================================
  # Massachusetts Banks (10)
  # ========================================
  
  - id: eastern_bank
    name: Eastern Bank
    org_type: bank
    homepage_url: https://www.easternbank.com/
    url: https://www.easternbank.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: rockland_trust
    name: Rockland Trust
    org_type: bank
    homepage_url: https://www.rocklandtrust.com/
    rate_url: https://www.rocklandtrust.com/personal/home-financing/residential-mortgages
    parser_key: rockland_trust
    enabled: true
    tags: [MA_local, bank]
    
  - id: cambridge_savings
    name: Cambridge Savings Bank
    org_type: bank
    homepage_url: https://www.cambridgesavings.com/
    url: https://www.cambridgesavings.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: middlesex_savings
    name: Middlesex Savings Bank
    org_type: bank
    homepage_url: https://www.middlesexbank.com/
    url: https://www.middlesexbank.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: salem_five
    name: Salem Five Bank
    org_type: bank
    homepage_url: https://www.salemfive.com/
    url: https://www.salemfive.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: needham_bank
    name: Needham Bank
    org_type: bank
    homepage_url: https://www.needhambank.com/
    url: https://www.needhambank.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: cape_cod_5
    name: Cape Cod 5
    org_type: bank
    homepage_url: https://www.capecodfive.com/
    url: https://www.capecodfive.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: berkshire_bank
    name: Berkshire Bank
    org_type: bank
    homepage_url: https://www.berkshirebank.com/
    url: https://www.berkshirebank.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: brookline_bank
    name: Brookline Bank
    org_type: bank
    homepage_url: https://www.brooklinebank.com/
    url: https://www.brooklinebank.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  - id: harborone_bank
    name: HarborOne Bank
    org_type: bank
    homepage_url: https://www.harborone.com/
    url: https://www.harborone.com/
    method: none
    enabled: false
    tags: [MA_local, bank]
    
  # ========================================
  # Nationwide Credit Unions (10)
  # ========================================
  
  - id: navy_federal
    name: Navy Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.navyfederal.org/
    rate_url: https://www.navyfederal.org/loans-cards/mortgage/mortgage-rates.html
    parser_key: navy_federal
    enabled: true
    tags: [national, cu]
    
  - id: ncsecu
    name: State Employees' Credit Union (NCSECU)
    org_type: credit_union
    homepage_url: https://www.ncsecu.org/
    url: https://www.ncsecu.org/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: penfed
    name: PenFed Credit Union
    org_type: credit_union
    homepage_url: https://www.penfed.org/
    rate_url: https://www.penfed.org/mortgages/mortgage-rates
    parser_key: penfed
    enabled: false
    tags: [national, cu]
    notes: "Rate page times out or blocks scraping"
    
  - id: schoolsfirst_fcu
    name: SchoolsFirst FCU
    org_type: credit_union
    homepage_url: https://www.schoolsfirstfcu.org/
    url: https://www.schoolsfirstfcu.org/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: becu
    name: BECU
    org_type: credit_union
    homepage_url: https://www.becu.org/
    url: https://www.becu.org/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: golden1_cu
    name: Golden 1 Credit Union
    org_type: credit_union
    homepage_url: https://www.golden1.com/
    url: https://www.golden1.com/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: alliant_cu
    name: Alliant Credit Union
    org_type: credit_union
    homepage_url: https://www.alliantcreditunion.org/
    rate_url: https://www.alliantcreditunion.org/bank/mortgage-rates
    parser_key: alliant
    enabled: false
    tags: [national, cu]
    notes: "No static rate table found on page"
    
  - id: america_first_cu
    name: America First Credit Union (UT)
    org_type: credit_union
    homepage_url: https://www.americafirst.com/
    url: https://www.americafirst.com/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: first_tech_fcu
    name: First Tech Federal Credit Union
    org_type: credit_union
    homepage_url: https://www.firsttechfed.com/
    url: https://www.firsttechfed.com/
    method: none
    enabled: false
    tags: [national, cu]
    
  - id: patelco_cu
    name: Patelco Credit Union
    org_type: credit_union
    homepage_url: https://www.patelco.org/
    url: https://www.patelco.org/
    method: none
    enabled: false
    tags: [national, cu]
    
  # ========================================
  # Nationwide Lenders (15)
  # ========================================
  
  - id: uwm
    name: United Wholesale Mortgage (UWM)
    org_type: nonbank
    homepage_url: https://www.uwm.com/
    url: https://www.uwm.com/
    method: none
    enabled: false
    tags: [national, nonbank, wholesale]
    notes: "Wholesale/broker channel only"
    
  - id: rocket
    name: Rocket Mortgage
    org_type: nonbank
    homepage_url: https://www.rocketmortgage.com/
    url: https://www.rocketmortgage.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: pennymac
    name: Pennymac
    org_type: nonbank
    homepage_url: https://www.pennymac.com/
    url: https://www.pennymac.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: newrez
    name: Newrez
    org_type: nonbank
    homepage_url: https://www.newrez.com/
    url: https://www.newrez.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: mr_cooper
    name: Mr. Cooper
    org_type: nonbank
    homepage_url: https://www.mrcooper.com/
    url: https://www.mrcooper.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: loandepot
    name: loanDepot
    org_type: nonbank
    homepage_url: https://www.loandepot.com/
    url: https://www.loandepot.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: rate
    name: Rate (Guaranteed Rate)
    org_type: nonbank
    homepage_url: https://www.rate.com/
    url: https://www.rate.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: crosscountry
    name: CrossCountry Mortgage
    org_type: nonbank
    homepage_url: https://crosscountrymortgage.com/
    url: https://crosscountrymortgage.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: guild
    name: Guild Mortgage
    org_type: nonbank
    homepage_url: https://www.guildmortgage.com/
    url: https://www.guildmortgage.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: fairway
    name: Fairway Independent Mortgage
    org_type: nonbank
    homepage_url: https://www.fairway.com/
    url: https://www.fairway.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: movement
    name: Movement Mortgage
    org_type: nonbank
    homepage_url: https://movement.com/
    url: https://movement.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: freedom
    name: Freedom Mortgage
    org_type: nonbank
    homepage_url: https://www.freedommortgage.com/
    url: https://www.freedommortgage.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: amerihome
    name: AmeriHome Mortgage
    org_type: nonbank
    homepage_url: https://www.amerihome.com/
    url: https://www.amerihome.com/
    method: none
    enabled: false
    tags: [national, nonbank]
    
  - id: chase
    name: Chase (JPMorgan Chase)
    org_type: bank
    homepage_url: https://www.chase.com/
    url: https://www.chase.com/personal/mortgage
    method: none
    enabled: false
    tags: [national, bank]
    
  - id: wells_fargo
    name: Wells Fargo
    org_type: bank
    homepage_url: https://www.wellsfargo.com/
    url: https://www.wellsfargo.com/mortgage/
    method: none
    enabled: false
    tags: [national, bank]
